<?php
/**
 * SmsAvailability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sms4all
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sms4all\Model;

use \ArrayAccess;
/**
 * SmsAvailability Class Doc Comment
 *
 * @category    Class
 * @description Model for SmsAvailability
 * @package     Sms4all
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SmsAvailability implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'avaiblesms' => 'int',
        'avaiblesmsapi' => 'int',
        'avaiblesmsbo' => 'int',
        'code' => 'string',
        'validity' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'avaiblesms' => 'avaiblesms',
        'avaiblesmsapi' => 'avaiblesmsapi',
        'avaiblesmsbo' => 'avaiblesmsbo',
        'code' => 'code',
        'validity' => 'validity'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'avaiblesms' => 'setAvaiblesms',
        'avaiblesmsapi' => 'setAvaiblesmsapi',
        'avaiblesmsbo' => 'setAvaiblesmsbo',
        'code' => 'setCode',
        'validity' => 'setValidity'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'avaiblesms' => 'getAvaiblesms',
        'avaiblesmsapi' => 'getAvaiblesmsapi',
        'avaiblesmsbo' => 'getAvaiblesmsbo',
        'code' => 'getCode',
        'validity' => 'getValidity'
    );
  
    
    /**
      * $avaiblesms 
      * @var int
      */
    protected $avaiblesms;
    
    /**
      * $avaiblesmsapi 
      * @var int
      */
    protected $avaiblesmsapi;
    
    /**
      * $avaiblesmsbo 
      * @var int
      */
    protected $avaiblesmsbo;
    
    /**
      * $code 
      * @var string
      */
    protected $code;
    
    /**
      * $validity 
      * @var string
      */
    protected $validity;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->avaiblesms = $data["avaiblesms"];
            $this->avaiblesmsapi = $data["avaiblesmsapi"];
            $this->avaiblesmsbo = $data["avaiblesmsbo"];
            $this->code = $data["code"];
            $this->validity = $data["validity"];
        }
    }
    
    /**
     * Gets avaiblesms
     * @return int
     */
    public function getAvaiblesms()
    {
        return $this->avaiblesms;
    }
  
    /**
     * Sets avaiblesms
     * @param int $avaiblesms 
     * @return $this
     */
    public function setAvaiblesms($avaiblesms)
    {
        
        $this->avaiblesms = $avaiblesms;
        return $this;
    }
    
    /**
     * Gets avaiblesmsapi
     * @return int
     */
    public function getAvaiblesmsapi()
    {
        return $this->avaiblesmsapi;
    }
  
    /**
     * Sets avaiblesmsapi
     * @param int $avaiblesmsapi 
     * @return $this
     */
    public function setAvaiblesmsapi($avaiblesmsapi)
    {
        
        $this->avaiblesmsapi = $avaiblesmsapi;
        return $this;
    }
    
    /**
     * Gets avaiblesmsbo
     * @return int
     */
    public function getAvaiblesmsbo()
    {
        return $this->avaiblesmsbo;
    }
  
    /**
     * Sets avaiblesmsbo
     * @param int $avaiblesmsbo 
     * @return $this
     */
    public function setAvaiblesmsbo($avaiblesmsbo)
    {
        
        $this->avaiblesmsbo = $avaiblesmsbo;
        return $this;
    }
    
    /**
     * Gets code
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }
  
    /**
     * Sets code
     * @param string $code 
     * @return $this
     */
    public function setCode($code)
    {
        
        $this->code = $code;
        return $this;
    }
    
    /**
     * Gets validity
     * @return string
     */
    public function getValidity()
    {
        return $this->validity;
    }
  
    /**
     * Sets validity
     * @param string $validity 
     * @return $this
     */
    public function setValidity($validity)
    {
        
        $this->validity = $validity;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Sms4all\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Sms4all\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
