<?php
/**
 * SmsreportApi
 * PHP version 5
 *
 * @category Class
 * @package  Sms4all
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Sms4all\Api;

use \Sms4all\Configuration;
use \Sms4all\ApiClient;
use \Sms4all\ApiException;
use \Sms4all\ObjectSerializer;

/**
 * SmsreportApi Class Doc Comment
 *
 * @category Class
 * @package  Sms4all
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsreportApi
{

    /**
     * API Client
     * @var \Sms4all\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Sms4all\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://sms4all.org:3030/apis');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Sms4all\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Sms4all\ApiClient $apiClient set the API client
     * @return SmsreportApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * smsReport
     *
     * 
     *
     * @param string $code code (required)
     * @param string $msgid msgid (required)
     * @return \Sms4all\Model\SmsReport
     * @throws \Sms4all\ApiException on non-2xx response
     */
    public function smsReport($code, $msgid)
    {
        list($response, $statusCode, $httpHeader) = $this->smsReportWithHttpInfo ($code, $msgid);
        return $response; 
    }


    /**
     * smsReportWithHttpInfo
     *
     * 
     *
     * @param string $code code (required)
     * @param string $msgid msgid (required)
     * @return Array of \Sms4all\Model\SmsReport, HTTP status code, HTTP response headers (array of strings)
     * @throws \Sms4all\ApiException on non-2xx response
     */
    public function smsReportWithHttpInfo($code, $msgid)
    {
        
        // verify the required parameter 'code' is set
        if ($code === null) {
            throw new \InvalidArgumentException('Missing the required parameter $code when calling smsReport');
        }
        // verify the required parameter 'msgid' is set
        if ($msgid === null) {
            throw new \InvalidArgumentException('Missing the required parameter $msgid when calling smsReport');
        }
  
        // parse inputs
        $resourcePath = "/smsreport";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array());
  
        // query params
        
        if ($code !== null) {
            $queryParams['code'] = $this->apiClient->getSerializer()->toQueryValue($code);
        }// query params
        
        if ($msgid !== null) {
            $queryParams['msgid'] = $this->apiClient->getSerializer()->toQueryValue($msgid);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Sms4all\Model\SmsReport'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Sms4all\ObjectSerializer::deserialize($response, '\Sms4all\Model\SmsReport', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Sms4all\ObjectSerializer::deserialize($e->getResponseBody(), '\Sms4all\Model\SmsReport', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
