<?php return array (
  'bootnetcrasher\\house\\Plugin' => 'plugins/bootnetcrasher/house/Plugin.php',
  'bootnetcrasher\\parametre\\Plugin' => 'plugins/bootnetcrasher/parametre/Plugin.php',
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'rainlab\\builder\\Plugin' => 'plugins/rainlab/builder/Plugin.php',
  'rainlab\\user\\Plugin' => 'plugins/rainlab/user/Plugin.php',
  'toughdeveloper\\imageresizer\\Plugin' => 'plugins/toughdeveloper/imageresizer/Plugin.php',
  'RainLab\\User\\Classes\\UserRedirector' => 'plugins/rainlab/user/classes/UserRedirector.php',
  'RainLab\\User\\Components\\Account' => 'plugins/rainlab/user/components/Account.php',
  'bootnetcrasher\\House\\Components\\Home' => 'plugins/bootnetcrasher/house/components/Home.php',
  'RainLab\\User\\Facades\\Auth' => 'plugins/rainlab/user/facades/Auth.php',
  'RainLab\\User\\Classes\\AuthManager' => 'plugins/rainlab/user/classes/AuthManager.php',
  'RainLab\\User\\Models\\Settings' => 'plugins/rainlab/user/models/Settings.php',
  'RainLab\\User\\Models\\User' => 'plugins/rainlab/user/models/User.php',
  'RainLab\\User\\Models\\Throttle' => 'plugins/rainlab/user/models/Throttle.php',
  'bootnetcrasher\\Parametre\\Models\\LocalisationModel' => 'plugins/bootnetcrasher/parametre/models/LocalisationModel.php',
  'Bootnetcrasher\\Parametre\\Models\\TypePublicationModel' => 'plugins/bootnetcrasher/parametre/models/TypePublicationModel.php',
  'bootnetcrasher\\House\\Models\\PublicationModel' => 'plugins/bootnetcrasher/house/models/PublicationModel.php',
);